import { Inter } from "next/font/google";
import Header from "@/components/Header";
import { createClient } from "@/utils/supabase/server";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = createClient();

  const { data, error } = await supabase.auth.getUser();
  if (error || !data?.user) {
    redirect("/auth");
  }

  const {
    data: { user },
    error: err,
  } = await supabase.auth.getUser();

  async function checkUserAndGetData(userId) {
    try {
      const { data, error } = await supabase
        .from("users")
        .select("*")
        .eq("id", userId)
        .limit(1)
        .single();

      if (error) {
        console.error("Error checking user ID:", error);
        return { exists: false, userData: null };
      }

      return { exists: data ? true : false, userData: data };
    } catch (error) {
      console.error("Unexpected error:", error);
      return { exists: false, userData: null };
    }
  }

  const { exists: isOnboarded, userData } = await checkUserAndGetData(user.id);


  if (!isOnboarded) {
    redirect("/onboarding");
  }

  return (
    <main>
      <Header user={userData} />
      {children}
    </main>
  );
}
